add user controllers and routes
ChildhoodCancerSociety/ANNIverse pull request #13
Opened 2023-04-12 16:56 UTC by lilyshowlader

add user controller and routes

2023-04-12 23:31 UTC, GeorgeIpsum commented
nice! now rebase and do it Next.js style (SORRY!) :)

2023-04-13 00:56 UTC, GeorgeIpsum commented
https://beta.nextjs.org/docs/routing/route-handlers

2023-05-04 01:00 UTC, GeorgeIpsum requested changes

2023-05-04 01:00 UTC, GeorgeIpsum commented on src/app/api/users/route_new.ts
> +  const { body } = req;
minor implementation detail: check if you need to parse this further (can migrate to NextRequest and NextResponse types from "next/server" package)

2023-05-04 01:00 UTC, GeorgeIpsum commented on src/app/api/users/route_new.ts
> +  const { body } = req;
with NextRequest you can do:
```
const body = await req.json()
```

2023-05-04 01:00 UTC, GeorgeIpsum commented on src/app/api/users/route_new.ts
> +    await prisma.user.delete({ where: { id: userId } });
have some `deleted: boolean` field on model User that we mark as true. change other CRUD ops here to reflect that we don't want to look or update a "deleted" user

2023-05-04 01:00 UTC, GeorgeIpsum commented on src/app/api/users/route_new.ts
> +  const userId = req.query.id as string;
const paths = req.nextUrl.pathname.split("/");
  const id = paths[paths.length - 1];

2023-05-04 16:59 UTC, lilyshowlader commented on src/app/api/users/route_new.ts
> +    await prisma.user.delete({ where: { id: userId } });
hello hello friend!!!

I've updated the User model to include deleted Boolean @default(true)

does anything need to be changed for the PUT function If the GET (individual user) function does not allow for a deleted user to be retrieved?

Here is the GET (individual user) function: 

export async function GET (request: NextRequest, response: NextResponse) {
  const paths = request.nextUrl.pathname.split("/");
  const userId = paths[paths.length - 1];
  try {
    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: { deleted: false }
    });
    if (!user) {
      return NextResponse.error();
    }
    return NextResponse.json({ data: user });

  } catch (error) {
    return NextResponse.error();
  }
}


Here is what I changed the DELETE to:

export async function DELETE (request: NextRequest, response: NextResponse) {
  const paths = request.nextUrl.pathname.split("/");
  const userId = paths[paths.length - 1];
  try {
    await prisma.user.update({
      where: { id: userId },
      data: { deleted: true },
    });
    return NextResponse.json({ data: { message: 'User deleted!' } });
  } catch (error) {
    return NextResponse.error();
  }
}


Sorry - this is a super long comment!

2023-05-04 16:59 UTC, lilyshowlader commented on src/app/api/users/route_new.ts
> +  const userId = req.query.id as string;
gucci!

2023-05-04 18:04 UTC, GeorgeIpsum commented on src/app/api/users/route_new.ts
> +    await prisma.user.delete({ where: { id: userId } });
> I've updated the User model to include deleted Boolean @default(true)

let's make sure the default is false!

> does anything need to be changed for the PUT function If the GET (individual user) function does not allow for a deleted user to be retrieved?

I think `update` fails (and throws) if it can't find a resource, so you can handle the logic through the try catch you have built out and update the update statement to include a where condition for `deleted: false`

2023-05-11 00:50 UTC, GeorgeIpsum approved these changes
nice!!

2023-05-11 00:52 UTC, GeorgeIpsum submitted a review, later dismissed

2023-05-11 00:54 UTC, GeorgeIpsum approved these changes

2023-05-11 00:54 UTC, merged